language: python
python:
  - "3.8"
script:
  - python -c "import os;print(os.getenv('TEST'));print(os.environ)"
env:
  global:
    - secure: a09wAiV/mh+OdsCsHT1Tpu5IKi0mTDHbArZwZFSI+1UMC0G0ZWegX3etUBH0sbWdaOsC+eZOCAdKFVLuftLpQ9BmhNRD7qrtRwPgfAWhdl83o7A3G34QQh/JxznN7H3rtq5QoJDSMf5+qAyXXwRx4q4iPuSEc+5UAB9jsrkEcJt2oJxZbS1tv6WAeHwI6Qxe/MLTeYyNDd+8rtA538zCO6eo4V6SHV90lMOr2gZdpvC6kzpjdd0Z2rh78kVbW9uG9iPfSLPoLEHecqeUj+mHZMPinu3aTaztczZ0BFpNsxhGtgY53m64Pe+C/nCuEve09KOZGHirEVc7w5L5CjCIDw+CnIQZKt1qPlZ7ASnPsSAb+QERk5wcamLXKdc2F3lN3J8J9iwkQXnpuNXmY4MKmWTUjLAFggi40QeQuJcOvgPewikPr7psbZMKSeo+uNlS4RQ78dhb8FRVcHse+GHeiwne61L6DvZwsRPszq0PPhTkfKomPwGTE25p8Gz11MEau7i6al2WEP21VtFXdS2uIUURyAt4s/fALZUsE/SlJpI5FXVkdq3xhHUux9jtnRL6pwTMJH/PTXHAXvprIVNxTd6aXudZf49fSuMV6diVRRGZljjhMnQYhm6YZOzIb39qINdrGm5xqjPDs49AToUhhwMZSUagi/5yR9NYJo9o6HE=
